# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(max_length=20)),
                ('english_name', models.CharField(max_length=30)),
            ],
        ),
    ]
