# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_keyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='english_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='site',
            name='chinese_name',
        ),
    ]
