# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_auto_20160926_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
