# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_site_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='site',
            name='openTime',
            field=models.CharField(default='', max_length=30),
        ),
    ]
