# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_auto_20160929_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=1000)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.Site')),
            ],
        ),
    ]
