# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_siteview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='openTime',
            field=models.CharField(default='', max_length=100),
        ),
    ]
