# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0010_auto_20160929_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='info',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
