# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0011_auto_20160929_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='openTime',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
