# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0012_auto_20160929_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
