# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0013_site_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='open',
            new_name='isOpen',
        ),
        migrations.AddField(
            model_name='site',
            name='transportation',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
