# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0014_auto_20161002_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='transportation',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
    ]
