# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0016_site_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='boyAsset',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='childrenAsset',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='classmateAsset',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='coupleAsset',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='familyAsset',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='girlAsset',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
