# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0017_auto_20161031_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='boyAsset',
        ),
        migrations.RemoveField(
            model_name='site',
            name='childrenAsset',
        ),
        migrations.RemoveField(
            model_name='site',
            name='classmateAsset',
        ),
        migrations.RemoveField(
            model_name='site',
            name='coupleAsset',
        ),
        migrations.RemoveField(
            model_name='site',
            name='familyAsset',
        ),
        migrations.RemoveField(
            model_name='site',
            name='girlAsset',
        ),
    ]
