# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_auto_20161128_1317'),
        ('Site', '0018_auto_20161120_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Category.Category'),
        ),
    ]
