# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0019_site_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='category',
        ),
    ]
