# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_remove_site_category'),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='english_name',
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.Category'),
        ),
        migrations.AddField(
            model_name='tag',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.Site'),
        ),
    ]
