# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_auto_20160820_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='site',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
